### PR TITLE
Prevent error, when service class was defined as parameter.

### PR DESCRIPTION
**Pull request by amustaine**
| Q                  | A           |
|--------------------|-------------|
| PR Type            | bugfix    |
| Tests pass?        | n/a      |

### CODE REVIEW

**Comment by gremo** [comment]
Sure! Can you please check why travis is failing on resolveValue()?

**Comment by amustaine** [comment]
Sure, I will fix tests on this weekends.

**Comment by gremo** [comment]
Good, thanks for helping!

**Comment by gremo** [comment]
@amustaine any updates on this?

**Pull request merged**
